"""add

Revision ID: 8994b316d7ac
Revises: a99fa323581f
Create Date: 2022-06-12 21:27:38.817409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8994b316d7ac'
down_revision = 'a99fa323581f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
